In [18]:
# Required libraries
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.preprocessing as preprocessing
import pandas as pd
import numpy as np
from sklearn import metrics

In [13]:
#read dataset
dataset = pd.read_csv('school_grades_dataset.csv')

#Summarise the dataset

def summarise(df):
    for column in dataset.columns:
        print(column)
        if df.dtypes[column] == np.object:
            print("{}\n".format(df[column].value_counts()))
        else:
            print("{}\n".format(df[column].describe()))
        
        
summarise(dataset)

school
GP    423
MS    226
Name: school, dtype: int64

sex
F    383
M    266
Name: sex, dtype: int64

age
count    649.000000
mean      16.744222
std        1.218138
min       15.000000
25%       16.000000
50%       17.000000
75%       18.000000
max       22.000000
Name: age, dtype: float64

address
U    452
R    197
Name: address, dtype: int64

famsize
GT3    457
LE3    192
Name: famsize, dtype: int64

Pstatus
T    569
A     80
Name: Pstatus, dtype: int64

Medu
count    649.000000
mean       2.514638
std        1.134552
min        0.000000
25%        2.000000
50%        2.000000
75%        4.000000
max        4.000000
Name: Medu, dtype: float64

Fedu
count    649.000000
mean       2.306626
std        1.099931
min        0.000000
25%        1.000000
50%        2.000000
75%        3.000000
max        4.000000
Name: Fedu, dtype: float64

Mjob
other       258
services    136
at_home     135
teacher      72
health       48
Name: Mjob, dtype: int64

Fjob
other       367
services    181
at_home      42
teacher      36
health       23
Name: Fjob, dtype: int64

reason
course        285
home          149
reputation    143
other          72
Name: reason, dtype: int64

guardian
mother    455
father    153
other      41
Name: guardian, dtype: int64

traveltime
count    649.000000
mean       1.568567
std        0.748660
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        4.000000
Name: traveltime, dtype: float64

studytime
count    649.000000
mean       1.930663
std        0.829510
min        1.000000
25%        1.000000
50%        2.000000
75%        2.000000
max        4.000000
Name: studytime, dtype: float64

failures
count    649.000000
mean       0.221880
std        0.593235
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        3.000000
Name: failures, dtype: float64

schoolsup
no     581
yes     68
Name: schoolsup, dtype: int64

famsup
yes    398
no     251
Name: famsup, dtype: int64

paid
no     610
yes     39
Name: paid, dtype: int64

activities
no     334
yes    315
Name: activities, dtype: int64

nursery
yes    521
no     128
Name: nursery, dtype: int64

higher
yes    580
no      69
Name: higher, dtype: int64

internet
yes    498
no     151
Name: internet, dtype: int64

romantic
no     410
yes    239
Name: romantic, dtype: int64

famrel
count    649.000000
mean       3.930663
std        0.955717
min        1.000000
25%        4.000000
50%        4.000000
75%        5.000000
max        5.000000
Name: famrel, dtype: float64

freetime
count    649.000000
mean       3.180277
std        1.051093
min        1.000000
25%        3.000000
50%        3.000000
75%        4.000000
max        5.000000
Name: freetime, dtype: float64

goout
count    649.000000
mean       3.184900
std        1.175766
min        1.000000
25%        2.000000
50%        3.000000
75%        4.000000
max        5.000000
Name: goout, dtype: float64

Dalc
count    649.000000
mean       1.502311
std        0.924834
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        5.000000
Name: Dalc, dtype: float64

Walc
count    649.000000
mean       2.280431
std        1.284380
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max        5.000000
Name: Walc, dtype: float64

health
count    649.000000
mean       3.536210
std        1.446259
min        1.000000
25%        2.000000
50%        4.000000
75%        5.000000
max        5.000000
Name: health, dtype: float64

absences
count    649.000000
mean       3.659476
std        4.640759
min        0.000000
25%        0.000000
50%        2.000000
75%        6.000000
max       32.000000
Name: absences, dtype: float64

G1
count    649.000000
mean      11.399076
std        2.745265
min        0.000000
25%       10.000000
50%       11.000000
75%       13.000000
max       19.000000
Name: G1, dtype: float64

G2
count    649.000000
mean      11.570108
std        2.913639
min        0.000000
25%       10.000000
50%       11.000000
75%       13.000000
max       19.000000
Name: G2, dtype: float64

G3
count    649.000000
mean      11.906009
std        3.230656
min        0.000000
25%       10.000000
50%       12.000000
75%       14.000000
max       19.000000
Name: G3, dtype: float64

In [17]:
# Encode the data using LabelEncoder

def encodeData(df):
    result = df.copy()
    encoders = {}
    for column in df.columns:
        if df.dtypes[column] == np.object:
            encoders[column] = preprocessing.LabelEncoder()
            result[column] = encoders[column].fit_transform(result[column])
    return result, encoders

encoded_data, _ = encodeData(dataset)

print(encoded_data.head())

   school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob  Fjob  ...  \
0       0    0   18        1        0        0     4     4     0     4  ...
1       0    0   17        1        0        1     1     1     0     2  ...
2       0    0   15        1        1        1     1     1     0     2  ...
3       0    0   15        1        0        1     4     2     1     3  ...
4       0    0   16        1        0        1     3     3     2     2  ...

   famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3
0       4         3      4     1     1       3         4   0  11  11
1       5         3      3     1     1       3         2   9  11  11
2       4         3      2     2     3       3         6  12  13  12
3       3         2      2     1     1       5         0  14  14  14
4       4         3      2     1     2       5         0  11  13  13

[5 rows x 33 columns]

In [26]:
# Spliting the dataset

def getFeatures(df):
    features = []
    for column in df.columns:
        if column != 'G3':
            features.append(column)
    return features, 'G3'

features, output = getFeatures(encoded_data)

features = encoded_data[features]
output = encoded_data[output]

features_learn, features_test, output_learn, output_test = train_test_split(features, output, test_size=0.10, random_state=1)

['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2']

In [ ]:
# Initiate the learning

linreq = LinearRegression()
linreq.fit(features_learn, output_learn)

# Testing
output_predicted = linreq.predict(features_test)

print('Mean Absolute error = ', metrics.mean_absolute_error(output_test, output_predicted))